SELECT * FROM DUAl;



INSERT ALL
    INTO client (id_client, nume,prenume, id_adresa, email) VALUES (1,'Ion', 'Al Glanetasului', 1, 'IonSiPamantul@gmail.com')
    INTO client (id_client, nume,prenume, id_adresa, email) VALUES (2,'Marcel', 'Prichindelu', 2, 'Marcel2387@7yahoo.com')
    INTO client (id_client, nume,prenume, id_adresa, email) VALUES (3,'Horia', 'Scarlat', 3, 'pavelbartos@gmail.com')
    INTO client (id_client, nume,prenume, id_adresa, email) VALUES (4,'Radu', 'Marius', 4, 'n-am@gmail.com')
    INTO client (id_client, nume,prenume, id_adresa, email) VALUES (5,'John', 'Smith', 5, 'numeBasic@gmail.com')
SELECT 'Felicitari!!' FROM DUAL;

INSERT ALL
    INTO ticket (id_ticket, id_client,titlu, continut, ID_ANGAJAT ) VALUES (10, 1, 'Cum cumpar?', 'Cum cumpar un produs?', 2)
    INTO ticket (id_ticket, id_client,titlu, continut, ID_ANGAJAT ) VALUES (4, 1, 'Cum platesc?', 'Cum platesc un produs?', NULL)
    INTO ticket (id_ticket, id_client,titlu, continut, ID_ANGAJAT ) VALUES (5, 1, 'Salut ma poti ajuta?', 'Salut, ma poti ajuta?', NULL)
    INTO ticket (id_ticket, id_client,titlu, continut, ID_ANGAJAT ) VALUES (12, 4, 'Locatie sediu', 'Unde se afla sediul?', 2)
    INTO ticket (id_ticket, id_client,titlu, continut, ID_ANGAJAT ) VALUES (9, 4, 'Plata', 'Ce modalitati de plata exista??', 2)
    INTO reducere(id_reducere, DATA_INCEPUT,DATA_SFARSIT, tip, VALOARE) VALUES (4,'15-JAN-2004', '15-JAN-2006', 'procent', 15)
    INTO reducere(id_reducere, DATA_INCEPUT,DATA_SFARSIT, tip, VALOARE) VALUES (5,'15-FEB-2022', '24-SEP-2023', 'suma', 240)
    INTO reducere(id_reducere, DATA_INCEPUT,DATA_SFARSIT, tip, VALOARE) VALUES (6,'15-OCT-2022', '23-NOV-2022', 'procent', 15)
    INTO reducere(id_reducere, DATA_INCEPUT, tip, VALOARE) VALUES (7, '25-MAR-2022', 'procent', 10)
    INTO reducere(id_reducere, DATA_SFARSIT, tip, VALOARE) VALUES (8, '1-AUG-2022', 'suma', 69)
    INTO producator (ID_PRODUCATOR, nume, ID_ADRESA, email ) VALUES (1, 'Audio-Technica', 0, 'contact@audiotechnica.com')
    INTO producator (ID_PRODUCATOR, nume, ID_ADRESA, email ) VALUES (2, 'SENNHEISER', 0, 'contact@sennheiser.com')
    INTO producator (ID_PRODUCATOR, nume, ID_ADRESA, email ) VALUES (3, 'Shure', 0, 'shure@shure.com')
    INTO producator (ID_PRODUCATOR, nume, ID_ADRESA, email ) VALUES (4, 'Rode', 0, 'contact@rode.com')
    INTO producator (ID_PRODUCATOR, nume, ID_ADRESA, email ) VALUES (5, 'Behringer', 0, 'behringer@gmail.com')
    INTO producator (ID_PRODUCATOR, nume, ID_ADRESA, email ) VALUES (6, 'KZ Audio', 0, 'kz-audio@gmail.com')
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (1, 4, 'Podcaster', 840.50, 'microfon', NULL)
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (2, 4, 'PodMic', 455, 'microfon', NULL)
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (3, 3, 'SM58',400, 'microfon', NULL)
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (4, 2, 'HD 600', 1530, 'casti', NULL)
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (5, 1, 'ATH-M50x', 579.40, 'casti', NULL)
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (6, 1, 'ATH-M20x', 249.80, 'casti', 5)
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (7, 6, 'ZR10', 335, 'casti', NULL)
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (8, 1, 'ATH-M30x', 239.67, 'casti', NULL)
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (9, 5, 'C-1U', 229.99, 'microfon', NULL)
    INTO produs (id_produs, ID_PRODUCATOR,NUME, pret, TIP,ID_REDUCERE ) VALUES (10, 6, 'ZEX PRO', 230, 'casti', NULL)
    INTO microfon (id_produs, ID_MICROFON, TIP, conectivitate ) VALUES (9, 1, 'condensator', 'USB')
    INTO microfon (id_produs, ID_MICROFON, TIP, conectivitate ) VALUES (3, 2, 'dinamic', 'XLR')
    INTO microfon (id_produs, ID_MICROFON, TIP, conectivitate ) VALUES (2, 3, 'dinamic', 'XLR')
    INTO microfon (id_produs, ID_MICROFON, TIP, conectivitate ) VALUES (1, 4, 'condensator', 'XLR')
    INTO casti (id_produs, id_casti, TIP, conectivitate, NOISE_CANCELLING ) VALUES (4, 1,'Over Ear', 'cu fir', 1)
    INTO casti (id_produs, id_casti, TIP, conectivitate, NOISE_CANCELLING ) VALUES (5, 2,'Over Ear', 'cu fir', 0)
    INTO casti (id_produs, id_casti, TIP, conectivitate, NOISE_CANCELLING ) VALUES (6, 3,'Over Ear', 'cu fir', 0)
    INTO casti (id_produs, id_casti, TIP, conectivitate, NOISE_CANCELLING ) VALUES (7, 4,'In Ear', 'wireless', 1)
    INTO casti (id_produs, id_casti, TIP, conectivitate, NOISE_CANCELLING ) VALUES (8, 5,'Over Ear', 'wireless', 0)
    INTO casti (id_produs, id_casti, TIP, conectivitate, NOISE_CANCELLING ) VALUES (10, 6,'In Ear', 'cu fir', 1)
    INTO departament (ID_DEPARTAMENT, TITLU, ID_MANAGER, ID_ADRESA, email) VALUES (1, 'Vanzari',2, 2, 'contact@showroom.ro')
    INTO departament (ID_DEPARTAMENT, TITLU, ID_MANAGER, ID_ADRESA, email) VALUES (2, 'Impachetare comenzi',1, 2, 'contact@showroom.ro')
    INTO departament (ID_DEPARTAMENT, TITLU, ID_MANAGER, ID_ADRESA, email) VALUES (3, 'Website',2, 3, 'contact@showroom.ro')
    INTO departament (ID_DEPARTAMENT, TITLU, ID_MANAGER, ID_ADRESA, email) VALUES (4, 'Showroom',1, 2, 'contact@showroom.ro')
    INTO adresa (id_adresa,oras, strada, numar, apartament, COD_POSTAL) VALUES (1, 'Bucuresti','Alexandru Macedon', 14, 66, '071432')
    INTO adresa (id_adresa,oras, strada, numar, apartament, COD_POSTAL) VALUES (2, 'Bucuresti','Soldan Ion enache', 14, 66, '32498')
    INTO adresa (id_adresa,oras, strada, numar, apartament, COD_POSTAL) VALUES (3, 'Bucuresti','I C Bratianu', 14, 66, '139821')
    INTO adresa (id_adresa,oras, strada, numar, apartament, COD_POSTAL) VALUES (4, 'Bucuresti','Iuliu Maniu', 66, NULL, '23873')
    INTO adresa (id_adresa,oras, strada, numar, apartament, COD_POSTAL) VALUES (5, 'Bucuresti','Splaiul Independentei', 145, NULL, '071432')
    INTO adresa (id_adresa,oras, strada, numar, apartament, COD_POSTAL) VALUES (6, 'Bucuresti','Straduintei', 12, 66, '091380')
    INTO adresa (id_adresa,oras, strada, numar, apartament, COD_POSTAL) VALUES (7, 'Bucuresti','Aliorului', 5, 66, '231234')
    INTO angajat (ID_ANGAJAT, ID_DEPARTAMENT, nume, prenume, ID_ADRESA, SALARIU, email) VALUES (2, 1,'Andrei', 'Balea', 7, 7500, 'emailGeneric@gmail.com')
    INTO angajat (ID_ANGAJAT, ID_DEPARTAMENT, nume, prenume, ID_ADRESA, email) VALUES (1, 4,'Marian', 'Popovici', 7, 'emailGeneric@gmail.com')
    INTO angajat (ID_ANGAJAT, ID_DEPARTAMENT, nume, prenume, ID_ADRESA, SALARIU, email) VALUES (3, 3,'Theodor', 'Ionescu', 7, 1200, 'emailGeneric@gmail.com')
    INTO angajat (ID_ANGAJAT, ID_DEPARTAMENT, nume, prenume, ID_ADRESA, SALARIU, email) VALUES (4, 2,'Theodora', 'Apostol', 7, 4800, 'emailGeneric@gmail.com')
    INTO angajat (ID_ANGAJAT, ID_DEPARTAMENT, nume, prenume, ID_ADRESA, SALARIU, email) VALUES (5, 2,'Gabriel', 'Popescu', 7, 5500, 'emailGeneric@gmail.com')
    INTO comanda (ID_COMANDA, ID_ADRESA, ID_ANGAJAT, ID_CLIENT, MENTIUNI) VALUES (1, 3,4, 1, 'Nu am nimic de declarat.')
    INTO comanda (ID_COMANDA, ID_ADRESA, ID_ANGAJAT, ID_CLIENT, MENTIUNI) VALUES (2, 4,4, 2, NULL)
    INTO comanda (ID_COMANDA, ID_ADRESA, ID_ANGAJAT, ID_CLIENT, MENTIUNI) VALUES (3, 5,4, 3, NULL)
    INTO comanda (ID_COMANDA, ID_ADRESA, ID_ANGAJAT, ID_CLIENT, MENTIUNI) VALUES (4, 2,4, 2, NULL)
    INTO comanda (ID_COMANDA, ID_ADRESA, ID_ANGAJAT, ID_CLIENT, MENTIUNI) VALUES (5, 3,4, 1, NULL)
    INTO comanda (ID_COMANDA, ID_ADRESA, ID_ANGAJAT, ID_CLIENT, MENTIUNI) VALUES (6, 3,4, 1, 'Sa impachetati discret.')
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (1, 3)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (2, 4)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (3, 5)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (4, 2)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (5, 7)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (6, 3)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (1, 5)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (1, 1)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (2, 9)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (3, 8)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (4, 6)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (5, 4)
    INTO PRODUS_COMANDAT(ID_COMANDA, ID_PRODUS) VALUES (4, 5)
SELECT 'Distractie!!!' FROM DUAL;